#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'runit'
cookbook 'ohai'
cookbook 'git'
cookbook 'openssl'
cookbook 'redis'